### PR TITLE
implement a simple factor and simplify algorithm for equations

### PR DESCRIPTION
**Pull request by vdwees**
@jackvreeken What do you think of this solution to #39 ?

### CODE REVIEW

**Comment by jackvreeken** [comment]
The first thing I thought of when you opened the issue was to use derivatives to check equality. Take the derivative of the equation to its first variable, and compare that to the derivative to the second variable. That would work for the example you gave in the issue, but probably won't when `sq()` / `exp()` etc. are part of the equation.

Old but related discussion over at CasADi: https://github.com/casadi/casadi/issues/1540

**Comment by jackvreeken** [comment]
Another idea:

```Python
vars = ca.symvar(eq)
if len(vars) == 2:
    if ca.substitute(eq, vars[0], vars[1]).is_zero():
        # They are aliases!
        make_vars_aliases()
```

**Comment by vdwees** [comment]
As you mentioned, it is slow and expensive. But I am also not sure it does what we want either- my objective for this algorithm is to simplify equations, not detect aliases. For example, `(0.48 *(A + B))/200` should be simplified to `A+B`. Whether we alias `A` to `B` or not, the simplified equation is a huge improvement from a numerical point of view.

**Comment by jackvreeken** [comment]
Ah, I get what you mean. Your implementation looks like a good start. Does it also work with something like ```3600 * x + 3600 * y```? 

I would definitely like to check with @jgillis eventually, but if you already know now that it saves a lot of computations, I wouldn't be against merging what you made now.

**Comment by vdwees** [comment]
No it does not. But it isn't common for that to happen unless the equation is written like that in the .mo
Still, it would be nice to catch that too.

**Comment by vdwees** [comment]
Lets make the default behaviour to not do this simplification and then merge it.

**Comment by vdwees** [comment]
@jackvreeken Can you squash commits when merging?

**Pull request merged**
