### PR TITLE
CasADi backend support for unspecified dimensions

### LINKED ISSUE #54: Add support for unspecified dimensions to parser
```Modelica
model A
  parameter Real x[:, :] = {{0.0}};
end A;
```
or 
```Modelica
model A
  parameter Real x[:, :];
end A;

model B
  A a(x = {{88.3224,  281.642,  143.011},
                {58.8183,  -24.9845,   0.0},
                {-1.45483,   0.0,      0.0}});
end B;
```

### PR DESCRIPTION
**Pull request by jackvreeken**
If a symbol does not have all dimensions specified, its value must have.

Closes #54

### CODE REVIEW

**Comment by vdwees** [comment]
@jackvreeken the tests failed on this one. Also, the line

```python
if None in itertools.chain.from_iterable((x.start, x.stop) for x in shape if isinstance(x, slice)):
```

could use a comment or refactoring- it is hard to read.

**Comment by jackvreeken** [comment]
Yep, blindly merging in changes using GitHub will break tests 😉 I'll properly rebase on top of the recent test folder change, and add a comment for that line.

**Comment by vdwees** [comment]
Hmm yes I tried out the "update branch" button and it did a merge... 0/10 would not recommend.

**Comment by jackvreeken** [comment]
- [ ] ```Real A[:,2];```

**Pull request merged**
